<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PacienteCausaMuerte', 'doctrine');

/**
 * BasePacienteCausaMuerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $detalles
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getDetalles() Returns the current record's "detalles" value
 * @method PacienteCausaMuerte setId()       Sets the current record's "id" value
 * @method PacienteCausaMuerte setDetalles() Sets the current record's "detalles" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePacienteCausaMuerte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente_causa_muerte');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('detalles', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}