<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Datosutiles', 'doctrine');

/**
 * BaseDatosutiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $password
 * @property timestamp $fecha
 * @property integer $root
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method string      getPassword() Returns the current record's "password" value
 * @method timestamp   getFecha()    Returns the current record's "fecha" value
 * @method integer     getRoot()     Returns the current record's "root" value
 * @method Datosutiles setId()       Sets the current record's "id" value
 * @method Datosutiles setPassword() Sets the current record's "password" value
 * @method Datosutiles setFecha()    Sets the current record's "fecha" value
 * @method Datosutiles setRoot()     Sets the current record's "root" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatosutiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('datosutiles');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'pass',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('root', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}