<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DonanteOrganos', 'doctrine');

/**
 * BaseDonanteOrganos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_donante
 * @property string $organo
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method string         getIdDonante()  Returns the current record's "id_donante" value
 * @method string         getOrgano()     Returns the current record's "organo" value
 * @method DonanteOrganos setId()         Sets the current record's "id" value
 * @method DonanteOrganos setIdDonante()  Sets the current record's "id_donante" value
 * @method DonanteOrganos setOrgano()     Sets the current record's "organo" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonanteOrganos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donante_organos');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_donante', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('organo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}