<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteTxtorax', 'doctrine');

/**
 * BaseEvolucionTrasplanteTxtorax
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property integer $rct
 * @property integer $foco
 * @property string $lateralizado
 * @property integer $derrame_pleural
 * @property string $lateral_derrame
 * @property integer $secuelas
 * @property string $otros
 * 
 * @method integer                    getIdtrasplante()    Returns the current record's "idtrasplante" value
 * @method date                       getFecha()           Returns the current record's "fecha" value
 * @method integer                    getRct()             Returns the current record's "rct" value
 * @method integer                    getFoco()            Returns the current record's "foco" value
 * @method string                     getLateralizado()    Returns the current record's "lateralizado" value
 * @method integer                    getDerramePleural()  Returns the current record's "derrame_pleural" value
 * @method string                     getLateralDerrame()  Returns the current record's "lateral_derrame" value
 * @method integer                    getSecuelas()        Returns the current record's "secuelas" value
 * @method string                     getOtros()           Returns the current record's "otros" value
 * @method EvolucionTrasplanteTxtorax setIdtrasplante()    Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteTxtorax setFecha()           Sets the current record's "fecha" value
 * @method EvolucionTrasplanteTxtorax setRct()             Sets the current record's "rct" value
 * @method EvolucionTrasplanteTxtorax setFoco()            Sets the current record's "foco" value
 * @method EvolucionTrasplanteTxtorax setLateralizado()    Sets the current record's "lateralizado" value
 * @method EvolucionTrasplanteTxtorax setDerramePleural()  Sets the current record's "derrame_pleural" value
 * @method EvolucionTrasplanteTxtorax setLateralDerrame()  Sets the current record's "lateral_derrame" value
 * @method EvolucionTrasplanteTxtorax setSecuelas()        Sets the current record's "secuelas" value
 * @method EvolucionTrasplanteTxtorax setOtros()           Sets the current record's "otros" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteTxtorax extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_txtorax');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rct', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('foco', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lateralizado', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('derrame_pleural', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lateral_derrame', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('secuelas', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('otros', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}