<?php

/**
 * BaseNefropatia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Pacientes
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getPacientes() Returns the current record's "Pacientes" collection
 * @method Nefropatia          setId()        Sets the current record's "id" value
 * @method Nefropatia          setNombre()    Sets the current record's "nombre" value
 * @method Nefropatia          setPacientes() Sets the current record's "Pacientes" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNefropatia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nefropatia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pacientes', array(
             'local' => 'id',
             'foreign' => 'nefropatia_id'));
    }
}