<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplante', 'doctrine');

/**
 * BaseEvolucionTrasplante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property float $pas
 * @property float $pad
 * @property float $diuresis
 * @property float $peso
 * @property float $urea
 * @property float $creatinina
 * @property float $ht
 * @property float $hb
 * @property float $gb
 * @property float $plaquetas
 * @property float $sodio
 * @property float $potasio
 * @property float $cloro
 * @property float $calcio
 * @property float $fosforo
 * @property float $glicemia
 * @property float $uricemia
 * @property float $prot_u
 * @property float $ccreatinina
 * @property float $curea
 * @property float $na_u
 * @property float $k_u
 * @property float $cya_pv
 * @property float $cya_pp
 * @property float $fk_p
 * @property float $mfm_p
 * @property float $eve_p
 * @property float $bd
 * @property float $bi
 * @property float $tgo
 * @property float $tgp
 * @property float $gammagt
 * @property float $f_alc
 * @property float $t_prot
 * @property float $kptt
 * @property float $howell
 * @property float $fibrinogeno
 * @property float $colesterol
 * @property float $hdl
 * @property float $ldl
 * @property float $r_at
 * @property float $tg
 * @property float $hna1c
 * @property float $albumina
 * @property float $globulinas
 * @property string $pthi
 * @property string $otros
 * @property float $numpthi
 * 
 * @method integer             getIdtrasplante() Returns the current record's "idtrasplante" value
 * @method date                getFecha()        Returns the current record's "fecha" value
 * @method float               getPas()          Returns the current record's "pas" value
 * @method float               getPad()          Returns the current record's "pad" value
 * @method float               getDiuresis()     Returns the current record's "diuresis" value
 * @method float               getPeso()         Returns the current record's "peso" value
 * @method float               getUrea()         Returns the current record's "urea" value
 * @method float               getCreatinina()   Returns the current record's "creatinina" value
 * @method float               getHt()           Returns the current record's "ht" value
 * @method float               getHb()           Returns the current record's "hb" value
 * @method float               getGb()           Returns the current record's "gb" value
 * @method float               getPlaquetas()    Returns the current record's "plaquetas" value
 * @method float               getSodio()        Returns the current record's "sodio" value
 * @method float               getPotasio()      Returns the current record's "potasio" value
 * @method float               getCloro()        Returns the current record's "cloro" value
 * @method float               getCalcio()       Returns the current record's "calcio" value
 * @method float               getFosforo()      Returns the current record's "fosforo" value
 * @method float               getGlicemia()     Returns the current record's "glicemia" value
 * @method float               getUricemia()     Returns the current record's "uricemia" value
 * @method float               getProtU()        Returns the current record's "prot_u" value
 * @method float               getCcreatinina()  Returns the current record's "ccreatinina" value
 * @method float               getCurea()        Returns the current record's "curea" value
 * @method float               getNaU()          Returns the current record's "na_u" value
 * @method float               getKU()           Returns the current record's "k_u" value
 * @method float               getCyaPv()        Returns the current record's "cya_pv" value
 * @method float               getCyaPp()        Returns the current record's "cya_pp" value
 * @method float               getFkP()          Returns the current record's "fk_p" value
 * @method float               getMfmP()         Returns the current record's "mfm_p" value
 * @method float               getEveP()         Returns the current record's "eve_p" value
 * @method float               getBd()           Returns the current record's "bd" value
 * @method float               getBi()           Returns the current record's "bi" value
 * @method float               getTgo()          Returns the current record's "tgo" value
 * @method float               getTgp()          Returns the current record's "tgp" value
 * @method float               getGammagt()      Returns the current record's "gammagt" value
 * @method float               getFAlc()         Returns the current record's "f_alc" value
 * @method float               getTProt()        Returns the current record's "t_prot" value
 * @method float               getKptt()         Returns the current record's "kptt" value
 * @method float               getHowell()       Returns the current record's "howell" value
 * @method float               getFibrinogeno()  Returns the current record's "fibrinogeno" value
 * @method float               getColesterol()   Returns the current record's "colesterol" value
 * @method float               getHdl()          Returns the current record's "hdl" value
 * @method float               getLdl()          Returns the current record's "ldl" value
 * @method float               getRAt()          Returns the current record's "r_at" value
 * @method float               getTg()           Returns the current record's "tg" value
 * @method float               getHna1c()        Returns the current record's "hna1c" value
 * @method float               getAlbumina()     Returns the current record's "albumina" value
 * @method float               getGlobulinas()   Returns the current record's "globulinas" value
 * @method string              getPthi()         Returns the current record's "pthi" value
 * @method string              getOtros()        Returns the current record's "otros" value
 * @method float               getNumpthi()      Returns the current record's "numpthi" value
 * @method EvolucionTrasplante setIdtrasplante() Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplante setFecha()        Sets the current record's "fecha" value
 * @method EvolucionTrasplante setPas()          Sets the current record's "pas" value
 * @method EvolucionTrasplante setPad()          Sets the current record's "pad" value
 * @method EvolucionTrasplante setDiuresis()     Sets the current record's "diuresis" value
 * @method EvolucionTrasplante setPeso()         Sets the current record's "peso" value
 * @method EvolucionTrasplante setUrea()         Sets the current record's "urea" value
 * @method EvolucionTrasplante setCreatinina()   Sets the current record's "creatinina" value
 * @method EvolucionTrasplante setHt()           Sets the current record's "ht" value
 * @method EvolucionTrasplante setHb()           Sets the current record's "hb" value
 * @method EvolucionTrasplante setGb()           Sets the current record's "gb" value
 * @method EvolucionTrasplante setPlaquetas()    Sets the current record's "plaquetas" value
 * @method EvolucionTrasplante setSodio()        Sets the current record's "sodio" value
 * @method EvolucionTrasplante setPotasio()      Sets the current record's "potasio" value
 * @method EvolucionTrasplante setCloro()        Sets the current record's "cloro" value
 * @method EvolucionTrasplante setCalcio()       Sets the current record's "calcio" value
 * @method EvolucionTrasplante setFosforo()      Sets the current record's "fosforo" value
 * @method EvolucionTrasplante setGlicemia()     Sets the current record's "glicemia" value
 * @method EvolucionTrasplante setUricemia()     Sets the current record's "uricemia" value
 * @method EvolucionTrasplante setProtU()        Sets the current record's "prot_u" value
 * @method EvolucionTrasplante setCcreatinina()  Sets the current record's "ccreatinina" value
 * @method EvolucionTrasplante setCurea()        Sets the current record's "curea" value
 * @method EvolucionTrasplante setNaU()          Sets the current record's "na_u" value
 * @method EvolucionTrasplante setKU()           Sets the current record's "k_u" value
 * @method EvolucionTrasplante setCyaPv()        Sets the current record's "cya_pv" value
 * @method EvolucionTrasplante setCyaPp()        Sets the current record's "cya_pp" value
 * @method EvolucionTrasplante setFkP()          Sets the current record's "fk_p" value
 * @method EvolucionTrasplante setMfmP()         Sets the current record's "mfm_p" value
 * @method EvolucionTrasplante setEveP()         Sets the current record's "eve_p" value
 * @method EvolucionTrasplante setBd()           Sets the current record's "bd" value
 * @method EvolucionTrasplante setBi()           Sets the current record's "bi" value
 * @method EvolucionTrasplante setTgo()          Sets the current record's "tgo" value
 * @method EvolucionTrasplante setTgp()          Sets the current record's "tgp" value
 * @method EvolucionTrasplante setGammagt()      Sets the current record's "gammagt" value
 * @method EvolucionTrasplante setFAlc()         Sets the current record's "f_alc" value
 * @method EvolucionTrasplante setTProt()        Sets the current record's "t_prot" value
 * @method EvolucionTrasplante setKptt()         Sets the current record's "kptt" value
 * @method EvolucionTrasplante setHowell()       Sets the current record's "howell" value
 * @method EvolucionTrasplante setFibrinogeno()  Sets the current record's "fibrinogeno" value
 * @method EvolucionTrasplante setColesterol()   Sets the current record's "colesterol" value
 * @method EvolucionTrasplante setHdl()          Sets the current record's "hdl" value
 * @method EvolucionTrasplante setLdl()          Sets the current record's "ldl" value
 * @method EvolucionTrasplante setRAt()          Sets the current record's "r_at" value
 * @method EvolucionTrasplante setTg()           Sets the current record's "tg" value
 * @method EvolucionTrasplante setHna1c()        Sets the current record's "hna1c" value
 * @method EvolucionTrasplante setAlbumina()     Sets the current record's "albumina" value
 * @method EvolucionTrasplante setGlobulinas()   Sets the current record's "globulinas" value
 * @method EvolucionTrasplante setPthi()         Sets the current record's "pthi" value
 * @method EvolucionTrasplante setOtros()        Sets the current record's "otros" value
 * @method EvolucionTrasplante setNumpthi()      Sets the current record's "numpthi" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pas', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pad', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('diuresis', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('peso', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('urea', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('creatinina', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ht', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('hb', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('gb', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('plaquetas', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sodio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('potasio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cloro', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('calcio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fosforo', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('glicemia', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('uricemia', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('prot_u', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ccreatinina', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('curea', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('na_u', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('k_u', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cya_pv', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cya_pp', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fk_p', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('mfm_p', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('eve_p', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bd', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('bi', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tgo', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tgp', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('gammagt', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('f_alc', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('t_prot', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('kptt', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('howell', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fibrinogeno', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('colesterol', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('hdl', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ldl', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('r_at', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tg', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('hna1c', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('albumina', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('globulinas', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pthi', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('otros', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('numpthi', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}