<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Induccion', 'doctrine');

/**
 * BaseInduccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * 
 * @method integer   getId()   Returns the current record's "id" value
 * @method string    getTipo() Returns the current record's "tipo" value
 * @method Induccion setId()   Sets the current record's "id" value
 * @method Induccion setTipo() Sets the current record's "tipo" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInduccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('induccion');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('tipo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}