<?php

/**
 * BaseInmunosupresores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $TrasplanteInmunosupresores
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method string              getNombre()                     Returns the current record's "nombre" value
 * @method Doctrine_Collection getTrasplanteInmunosupresores() Returns the current record's "TrasplanteInmunosupresores" collection
 * @method Inmunosupresores    setId()                         Sets the current record's "id" value
 * @method Inmunosupresores    setNombre()                     Sets the current record's "nombre" value
 * @method Inmunosupresores    setTrasplanteInmunosupresores() Sets the current record's "TrasplanteInmunosupresores" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInmunosupresores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inmunosupresores');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TrasplanteInmunosupresores', array(
             'local' => 'id',
             'foreign' => 'inmunosupresores_id'));
    }
}