<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmvUsoEnfermedades', 'doctrine');

/**
 * BaseCmvUsoEnfermedades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trasplante
 * @property date $fecha
 * @property integer $cmvenfermedades
 * 
 * @method integer            getTrasplante()      Returns the current record's "trasplante" value
 * @method date               getFecha()           Returns the current record's "fecha" value
 * @method integer            getCmvenfermedades() Returns the current record's "cmvenfermedades" value
 * @method CmvUsoEnfermedades setTrasplante()      Sets the current record's "trasplante" value
 * @method CmvUsoEnfermedades setFecha()           Sets the current record's "fecha" value
 * @method CmvUsoEnfermedades setCmvenfermedades() Sets the current record's "cmvenfermedades" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmvUsoEnfermedades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cmv_uso_enfermedades');
        $this->hasColumn('trasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cmvenfermedades', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}