<?php

/**
 * BaseEvolucionTrasplanteEcodopler
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trasplante_id
 * @property date $fecha
 * @property enum $estructura
 * @property integer $dilatacion
 * @property integer $colecciones
 * @property enum $eje_arterial
 * @property enum $eje_venoso
 * @property enum $arteria_renal
 * @property enum $vena_renal
 * @property enum $anast_venosa
 * @property enum $anast_renosa
 * @property float $indice
 * @property string $otros
 * @property Trasplante $Trasplante
 * 
 * @method integer                      getId()            Returns the current record's "id" value
 * @method integer                      getTrasplanteId()  Returns the current record's "trasplante_id" value
 * @method date                         getFecha()         Returns the current record's "fecha" value
 * @method enum                         getEstructura()    Returns the current record's "estructura" value
 * @method integer                      getDilatacion()    Returns the current record's "dilatacion" value
 * @method integer                      getColecciones()   Returns the current record's "colecciones" value
 * @method enum                         getEjeArterial()   Returns the current record's "eje_arterial" value
 * @method enum                         getEjeVenoso()     Returns the current record's "eje_venoso" value
 * @method enum                         getArteriaRenal()  Returns the current record's "arteria_renal" value
 * @method enum                         getVenaRenal()     Returns the current record's "vena_renal" value
 * @method enum                         getAnastVenosa()   Returns the current record's "anast_venosa" value
 * @method enum                         getAnastRenosa()   Returns the current record's "anast_renosa" value
 * @method float                        getIndice()        Returns the current record's "indice" value
 * @method string                       getOtros()         Returns the current record's "otros" value
 * @method Trasplante                   getTrasplante()    Returns the current record's "Trasplante" value
 * @method EvolucionTrasplanteEcodopler setId()            Sets the current record's "id" value
 * @method EvolucionTrasplanteEcodopler setTrasplanteId()  Sets the current record's "trasplante_id" value
 * @method EvolucionTrasplanteEcodopler setFecha()         Sets the current record's "fecha" value
 * @method EvolucionTrasplanteEcodopler setEstructura()    Sets the current record's "estructura" value
 * @method EvolucionTrasplanteEcodopler setDilatacion()    Sets the current record's "dilatacion" value
 * @method EvolucionTrasplanteEcodopler setColecciones()   Sets the current record's "colecciones" value
 * @method EvolucionTrasplanteEcodopler setEjeArterial()   Sets the current record's "eje_arterial" value
 * @method EvolucionTrasplanteEcodopler setEjeVenoso()     Sets the current record's "eje_venoso" value
 * @method EvolucionTrasplanteEcodopler setArteriaRenal()  Sets the current record's "arteria_renal" value
 * @method EvolucionTrasplanteEcodopler setVenaRenal()     Sets the current record's "vena_renal" value
 * @method EvolucionTrasplanteEcodopler setAnastVenosa()   Sets the current record's "anast_venosa" value
 * @method EvolucionTrasplanteEcodopler setAnastRenosa()   Sets the current record's "anast_renosa" value
 * @method EvolucionTrasplanteEcodopler setIndice()        Sets the current record's "indice" value
 * @method EvolucionTrasplanteEcodopler setOtros()         Sets the current record's "otros" value
 * @method EvolucionTrasplanteEcodopler setTrasplante()    Sets the current record's "Trasplante" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteEcodopler extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_ecodopler');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('estructura', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('dilatacion', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('colecciones', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('eje_arterial', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('eje_venoso', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('arteria_renal', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('vena_renal', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('anast_venosa', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('anast_renosa', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'Bien',
              1 => 'Mal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('indice', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             'length' => '',
             ));
        $this->hasColumn('otros', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trasplante', array(
             'local' => 'trasplante_id',
             'foreign' => 'id'));
    }
}