<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteNutricion', 'doctrine');

/**
 * BaseEvolucionTrasplanteNutricion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property integer $talla
 * @property integer $peso_deseado
 * @property string $estructura_osea
 * @property string $impresion
 * @property integer $peso_real
 * @property integer $p_tricipital
 * @property string $p_tricipital_p
 * @property integer $p_subescapular
 * @property string $p_subescapular_p
 * @property integer $sum_pliegues
 * @property string $p_sum_pliegues
 * @property integer $cf_brazo
 * @property string $p_cf_brazo
 * @property integer $cf_musc_brazo
 * @property string $p_cf_musc_brazo
 * @property integer $area_brazo
 * @property integer $area_musc_brazo
 * @property string $p_area_musc_brazo
 * @property integer $area_grasa_brazo
 * @property string $p_area_grasa_brazo
 * @property integer $r_cintura_cadera
 * @property string $diag_nutricional
 * 
 * @method integer                      getIdtrasplante()       Returns the current record's "idtrasplante" value
 * @method date                         getFecha()              Returns the current record's "fecha" value
 * @method integer                      getTalla()              Returns the current record's "talla" value
 * @method integer                      getPesoDeseado()        Returns the current record's "peso_deseado" value
 * @method string                       getEstructuraOsea()     Returns the current record's "estructura_osea" value
 * @method string                       getImpresion()          Returns the current record's "impresion" value
 * @method integer                      getPesoReal()           Returns the current record's "peso_real" value
 * @method integer                      getPTricipital()        Returns the current record's "p_tricipital" value
 * @method string                       getPTricipitalP()       Returns the current record's "p_tricipital_p" value
 * @method integer                      getPSubescapular()      Returns the current record's "p_subescapular" value
 * @method string                       getPSubescapularP()     Returns the current record's "p_subescapular_p" value
 * @method integer                      getSumPliegues()        Returns the current record's "sum_pliegues" value
 * @method string                       getPSumPliegues()       Returns the current record's "p_sum_pliegues" value
 * @method integer                      getCfBrazo()            Returns the current record's "cf_brazo" value
 * @method string                       getPCfBrazo()           Returns the current record's "p_cf_brazo" value
 * @method integer                      getCfMuscBrazo()        Returns the current record's "cf_musc_brazo" value
 * @method string                       getPCfMuscBrazo()       Returns the current record's "p_cf_musc_brazo" value
 * @method integer                      getAreaBrazo()          Returns the current record's "area_brazo" value
 * @method integer                      getAreaMuscBrazo()      Returns the current record's "area_musc_brazo" value
 * @method string                       getPAreaMuscBrazo()     Returns the current record's "p_area_musc_brazo" value
 * @method integer                      getAreaGrasaBrazo()     Returns the current record's "area_grasa_brazo" value
 * @method string                       getPAreaGrasaBrazo()    Returns the current record's "p_area_grasa_brazo" value
 * @method integer                      getRCinturaCadera()     Returns the current record's "r_cintura_cadera" value
 * @method string                       getDiagNutricional()    Returns the current record's "diag_nutricional" value
 * @method EvolucionTrasplanteNutricion setIdtrasplante()       Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteNutricion setFecha()              Sets the current record's "fecha" value
 * @method EvolucionTrasplanteNutricion setTalla()              Sets the current record's "talla" value
 * @method EvolucionTrasplanteNutricion setPesoDeseado()        Sets the current record's "peso_deseado" value
 * @method EvolucionTrasplanteNutricion setEstructuraOsea()     Sets the current record's "estructura_osea" value
 * @method EvolucionTrasplanteNutricion setImpresion()          Sets the current record's "impresion" value
 * @method EvolucionTrasplanteNutricion setPesoReal()           Sets the current record's "peso_real" value
 * @method EvolucionTrasplanteNutricion setPTricipital()        Sets the current record's "p_tricipital" value
 * @method EvolucionTrasplanteNutricion setPTricipitalP()       Sets the current record's "p_tricipital_p" value
 * @method EvolucionTrasplanteNutricion setPSubescapular()      Sets the current record's "p_subescapular" value
 * @method EvolucionTrasplanteNutricion setPSubescapularP()     Sets the current record's "p_subescapular_p" value
 * @method EvolucionTrasplanteNutricion setSumPliegues()        Sets the current record's "sum_pliegues" value
 * @method EvolucionTrasplanteNutricion setPSumPliegues()       Sets the current record's "p_sum_pliegues" value
 * @method EvolucionTrasplanteNutricion setCfBrazo()            Sets the current record's "cf_brazo" value
 * @method EvolucionTrasplanteNutricion setPCfBrazo()           Sets the current record's "p_cf_brazo" value
 * @method EvolucionTrasplanteNutricion setCfMuscBrazo()        Sets the current record's "cf_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setPCfMuscBrazo()       Sets the current record's "p_cf_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaBrazo()          Sets the current record's "area_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaMuscBrazo()      Sets the current record's "area_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setPAreaMuscBrazo()     Sets the current record's "p_area_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaGrasaBrazo()     Sets the current record's "area_grasa_brazo" value
 * @method EvolucionTrasplanteNutricion setPAreaGrasaBrazo()    Sets the current record's "p_area_grasa_brazo" value
 * @method EvolucionTrasplanteNutricion setRCinturaCadera()     Sets the current record's "r_cintura_cadera" value
 * @method EvolucionTrasplanteNutricion setDiagNutricional()    Sets the current record's "diag_nutricional" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteNutricion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_nutricion');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('talla', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('peso_deseado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('estructura_osea', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('impresion', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('peso_real', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('p_tricipital', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('p_tricipital_p', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('p_subescapular', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('p_subescapular_p', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('sum_pliegues', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('p_sum_pliegues', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('cf_brazo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('p_cf_brazo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('cf_musc_brazo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('p_cf_musc_brazo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('area_brazo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('area_musc_brazo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('p_area_musc_brazo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('area_grasa_brazo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('p_area_grasa_brazo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('r_cintura_cadera', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('diag_nutricional', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}