<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteEcg', 'doctrine');

/**
 * BaseEvolucionTrasplanteEcg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property string $rs_ecg
 * @property string $hvi_ecg
 * @property string $onda_q_ecg
 * 
 * @method integer                getIdtrasplante() Returns the current record's "idtrasplante" value
 * @method date                   getFecha()        Returns the current record's "fecha" value
 * @method string                 getRsEcg()        Returns the current record's "rs_ecg" value
 * @method string                 getHviEcg()       Returns the current record's "hvi_ecg" value
 * @method string                 getOndaQEcg()     Returns the current record's "onda_q_ecg" value
 * @method EvolucionTrasplanteEcg setIdtrasplante() Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteEcg setFecha()        Sets the current record's "fecha" value
 * @method EvolucionTrasplanteEcg setRsEcg()        Sets the current record's "rs_ecg" value
 * @method EvolucionTrasplanteEcg setHviEcg()       Sets the current record's "hvi_ecg" value
 * @method EvolucionTrasplanteEcg setOndaQEcg()     Sets the current record's "onda_q_ecg" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteEcg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_ecg');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rs_ecg', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('hvi_ecg', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('onda_q_ecg', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}