<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tratamiento', 'doctrine');

/**
 * BaseTratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $the
 * @property integer $medicacion
 * @property string $dosis
 * @property date $fecha_inicio
 * @property date $fecha_fin
 * 
 * @method integer     getThe()          Returns the current record's "the" value
 * @method integer     getMedicacion()   Returns the current record's "medicacion" value
 * @method string      getDosis()        Returns the current record's "dosis" value
 * @method date        getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method date        getFechaFin()     Returns the current record's "fecha_fin" value
 * @method Tratamiento setThe()          Sets the current record's "the" value
 * @method Tratamiento setMedicacion()   Sets the current record's "medicacion" value
 * @method Tratamiento setDosis()        Sets the current record's "dosis" value
 * @method Tratamiento setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method Tratamiento setFechaFin()     Sets the current record's "fecha_fin" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTratamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tratamiento');
        $this->hasColumn('the', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('medicacion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('dosis', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}