<?php

/**
 * BaseDonanteSerol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $donante_id
 * @property integer $serol_id
 * @property integer $serol_valor_id
 * @property Donante $Donante
 * @property Serol $Serol
 * @property SerolValor $SerolValor
 * 
 * @method integer      getDonanteId()      Returns the current record's "donante_id" value
 * @method integer      getSerolId()        Returns the current record's "serol_id" value
 * @method integer      getSerolValorId()   Returns the current record's "serol_valor_id" value
 * @method Donante      getDonante()        Returns the current record's "Donante" value
 * @method Serol        getSerol()          Returns the current record's "Serol" value
 * @method SerolValor   getSerolValor()     Returns the current record's "SerolValor" value
 * @method DonanteSerol setDonanteId()      Sets the current record's "donante_id" value
 * @method DonanteSerol setSerolId()        Sets the current record's "serol_id" value
 * @method DonanteSerol setSerolValorId()   Sets the current record's "serol_valor_id" value
 * @method DonanteSerol setDonante()        Sets the current record's "Donante" value
 * @method DonanteSerol setSerol()          Sets the current record's "Serol" value
 * @method DonanteSerol setSerolValor()     Sets the current record's "SerolValor" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonanteSerol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donante_serol');
        $this->hasColumn('donante_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('serol_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('serol_valor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Donante', array(
             'local' => 'donante_id',
             'foreign' => 'id'));

        $this->hasOne('Serol', array(
             'local' => 'serol_id',
             'foreign' => 'id'));

        $this->hasOne('SerolValor', array(
             'local' => 'serol_valor_id',
             'foreign' => 'id'));
    }
}