<?php

/**
 * BaseEvolucionTrasplanteNutricion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trasplante_id
 * @property date $fecha
 * @property integer $talla
 * @property integer $peso_deseado
 * @property enum $estructura_osea
 * @property enum $impresion
 * @property integer $peso_real
 * @property integer $p_tricipital
 * @property enum $p_tricipital_p
 * @property integer $p_subescapular
 * @property enum $p_subescapular_p
 * @property integer $sum_pliegues
 * @property enum $p_sum_pliegues
 * @property integer $cf_brazo
 * @property enum $p_cf_brazo
 * @property integer $cf_musc_brazo
 * @property enum $p_cf_musc_brazo
 * @property integer $area_brazo
 * @property integer $area_musc_brazo
 * @property enum $p_area_musc_brazo
 * @property integer $area_grasa_brazo
 * @property enum $p_area_grasa_brazo
 * @property integer $r_cintura_cadera
 * @property enum $diag_nutricional
 * @property Trasplante $Trasplante
 * 
 * @method integer                      getId()                 Returns the current record's "id" value
 * @method integer                      getTrasplanteId()       Returns the current record's "trasplante_id" value
 * @method date                         getFecha()              Returns the current record's "fecha" value
 * @method integer                      getTalla()              Returns the current record's "talla" value
 * @method integer                      getPesoDeseado()        Returns the current record's "peso_deseado" value
 * @method enum                         getEstructuraOsea()     Returns the current record's "estructura_osea" value
 * @method enum                         getImpresion()          Returns the current record's "impresion" value
 * @method integer                      getPesoReal()           Returns the current record's "peso_real" value
 * @method integer                      getPTricipital()        Returns the current record's "p_tricipital" value
 * @method enum                         getPTricipitalP()       Returns the current record's "p_tricipital_p" value
 * @method integer                      getPSubescapular()      Returns the current record's "p_subescapular" value
 * @method enum                         getPSubescapularP()     Returns the current record's "p_subescapular_p" value
 * @method integer                      getSumPliegues()        Returns the current record's "sum_pliegues" value
 * @method enum                         getPSumPliegues()       Returns the current record's "p_sum_pliegues" value
 * @method integer                      getCfBrazo()            Returns the current record's "cf_brazo" value
 * @method enum                         getPCfBrazo()           Returns the current record's "p_cf_brazo" value
 * @method integer                      getCfMuscBrazo()        Returns the current record's "cf_musc_brazo" value
 * @method enum                         getPCfMuscBrazo()       Returns the current record's "p_cf_musc_brazo" value
 * @method integer                      getAreaBrazo()          Returns the current record's "area_brazo" value
 * @method integer                      getAreaMuscBrazo()      Returns the current record's "area_musc_brazo" value
 * @method enum                         getPAreaMuscBrazo()     Returns the current record's "p_area_musc_brazo" value
 * @method integer                      getAreaGrasaBrazo()     Returns the current record's "area_grasa_brazo" value
 * @method enum                         getPAreaGrasaBrazo()    Returns the current record's "p_area_grasa_brazo" value
 * @method integer                      getRCinturaCadera()     Returns the current record's "r_cintura_cadera" value
 * @method enum                         getDiagNutricional()    Returns the current record's "diag_nutricional" value
 * @method Trasplante                   getTrasplante()         Returns the current record's "Trasplante" value
 * @method EvolucionTrasplanteNutricion setId()                 Sets the current record's "id" value
 * @method EvolucionTrasplanteNutricion setTrasplanteId()       Sets the current record's "trasplante_id" value
 * @method EvolucionTrasplanteNutricion setFecha()              Sets the current record's "fecha" value
 * @method EvolucionTrasplanteNutricion setTalla()              Sets the current record's "talla" value
 * @method EvolucionTrasplanteNutricion setPesoDeseado()        Sets the current record's "peso_deseado" value
 * @method EvolucionTrasplanteNutricion setEstructuraOsea()     Sets the current record's "estructura_osea" value
 * @method EvolucionTrasplanteNutricion setImpresion()          Sets the current record's "impresion" value
 * @method EvolucionTrasplanteNutricion setPesoReal()           Sets the current record's "peso_real" value
 * @method EvolucionTrasplanteNutricion setPTricipital()        Sets the current record's "p_tricipital" value
 * @method EvolucionTrasplanteNutricion setPTricipitalP()       Sets the current record's "p_tricipital_p" value
 * @method EvolucionTrasplanteNutricion setPSubescapular()      Sets the current record's "p_subescapular" value
 * @method EvolucionTrasplanteNutricion setPSubescapularP()     Sets the current record's "p_subescapular_p" value
 * @method EvolucionTrasplanteNutricion setSumPliegues()        Sets the current record's "sum_pliegues" value
 * @method EvolucionTrasplanteNutricion setPSumPliegues()       Sets the current record's "p_sum_pliegues" value
 * @method EvolucionTrasplanteNutricion setCfBrazo()            Sets the current record's "cf_brazo" value
 * @method EvolucionTrasplanteNutricion setPCfBrazo()           Sets the current record's "p_cf_brazo" value
 * @method EvolucionTrasplanteNutricion setCfMuscBrazo()        Sets the current record's "cf_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setPCfMuscBrazo()       Sets the current record's "p_cf_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaBrazo()          Sets the current record's "area_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaMuscBrazo()      Sets the current record's "area_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setPAreaMuscBrazo()     Sets the current record's "p_area_musc_brazo" value
 * @method EvolucionTrasplanteNutricion setAreaGrasaBrazo()     Sets the current record's "area_grasa_brazo" value
 * @method EvolucionTrasplanteNutricion setPAreaGrasaBrazo()    Sets the current record's "p_area_grasa_brazo" value
 * @method EvolucionTrasplanteNutricion setRCinturaCadera()     Sets the current record's "r_cintura_cadera" value
 * @method EvolucionTrasplanteNutricion setDiagNutricional()    Sets the current record's "diag_nutricional" value
 * @method EvolucionTrasplanteNutricion setTrasplante()         Sets the current record's "Trasplante" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteNutricion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_nutricion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('talla', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('peso_deseado', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('estructura_osea', 'enum', 8, array(
             'type' => 'enum',
             'length' => 8,
             'values' => 
             array(
              0 => 'Pequeña',
              1 => 'Mediana',
              2 => 'Grande',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('impresion', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'Adelgazado',
              1 => 'Normopeso',
              2 => 'Sobrepeso',
              3 => 'Obesidad',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('peso_real', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('p_tricipital', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('p_tricipital_p', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('p_subescapular', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('p_subescapular_p', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('sum_pliegues', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('p_sum_pliegues', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('cf_brazo', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('p_cf_brazo', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('cf_musc_brazo', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('p_cf_musc_brazo', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('area_brazo', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('area_musc_brazo', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('p_area_musc_brazo', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('area_grasa_brazo', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('p_area_grasa_brazo', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => '<10',
              1 => '10-25',
              2 => '26-50',
              3 => '51-75',
              4 => '76-91',
              5 => '>90',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('r_cintura_cadera', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('diag_nutricional', 'enum', 13, array(
             'type' => 'enum',
             'length' => 13,
             'values' => 
             array(
              0 => 'Desnleve',
              1 => 'Desnmoderada',
              2 => 'Desnsevera',
              3 => 'Normopeso',
              4 => 'Sobrepeso',
              5 => 'Obesidad',
             ),
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trasplante', array(
             'local' => 'trasplante_id',
             'foreign' => 'id'));

        $evoluciontrasplantecounterbehavior0 = new EvolucionTrasplanteCounterBehavior();
        $this->actAs($evoluciontrasplantecounterbehavior0);
    }
}