<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SerolValor', 'doctrine');

/**
 * BaseSerolValor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $valor
 * 
 * @method integer    getId()    Returns the current record's "id" value
 * @method string     getValor() Returns the current record's "valor" value
 * @method SerolValor setId()    Sets the current record's "id" value
 * @method SerolValor setValor() Sets the current record's "valor" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSerolValor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('serol_valor');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('valor', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}