<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrasplanteInduccion', 'doctrine');

/**
 * BaseTrasplanteInduccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_trasplante
 * @property integer $id_induccion
 * @property integer $valor
 * 
 * @method integer             getIdTrasplante()  Returns the current record's "id_trasplante" value
 * @method integer             getIdInduccion()   Returns the current record's "id_induccion" value
 * @method integer             getValor()         Returns the current record's "valor" value
 * @method TrasplanteInduccion setIdTrasplante()  Sets the current record's "id_trasplante" value
 * @method TrasplanteInduccion setIdInduccion()   Sets the current record's "id_induccion" value
 * @method TrasplanteInduccion setValor()         Sets the current record's "valor" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteInduccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_induccion');
        $this->hasColumn('id_trasplante', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('id_induccion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('valor', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}