<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InjertoEvolucion', 'doctrine');

/**
 * BaseInjertoEvolucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pretrasplante
 * @property date $fecha
 * @property integer $tm
 * @property string $tm_cual
 * @property integer $gp_de_novo
 * @property integer $recidiva_gp_de_novo
 * @property integer $ra
 * @property integer $rc
 * @property integer $tratamiento
 * @property integer $trasplante
 * 
 * @method integer          getPretrasplante()       Returns the current record's "pretrasplante" value
 * @method date             getFecha()               Returns the current record's "fecha" value
 * @method integer          getTm()                  Returns the current record's "tm" value
 * @method string           getTmCual()              Returns the current record's "tm_cual" value
 * @method integer          getGpDeNovo()            Returns the current record's "gp_de_novo" value
 * @method integer          getRecidivaGpDeNovo()    Returns the current record's "recidiva_gp_de_novo" value
 * @method integer          getRa()                  Returns the current record's "ra" value
 * @method integer          getRc()                  Returns the current record's "rc" value
 * @method integer          getTratamiento()         Returns the current record's "tratamiento" value
 * @method integer          getTrasplante()          Returns the current record's "trasplante" value
 * @method InjertoEvolucion setPretrasplante()       Sets the current record's "pretrasplante" value
 * @method InjertoEvolucion setFecha()               Sets the current record's "fecha" value
 * @method InjertoEvolucion setTm()                  Sets the current record's "tm" value
 * @method InjertoEvolucion setTmCual()              Sets the current record's "tm_cual" value
 * @method InjertoEvolucion setGpDeNovo()            Sets the current record's "gp_de_novo" value
 * @method InjertoEvolucion setRecidivaGpDeNovo()    Sets the current record's "recidiva_gp_de_novo" value
 * @method InjertoEvolucion setRa()                  Sets the current record's "ra" value
 * @method InjertoEvolucion setRc()                  Sets the current record's "rc" value
 * @method InjertoEvolucion setTratamiento()         Sets the current record's "tratamiento" value
 * @method InjertoEvolucion setTrasplante()          Sets the current record's "trasplante" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInjertoEvolucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('injerto_evolucion');
        $this->hasColumn('pretrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tm', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tm_cual', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('gp_de_novo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('recidiva_gp_de_novo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ra', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rc', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tratamiento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('trasplante', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}