<?php

/**
 * BaseSerol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * @property Doctrine_Collection $DonanteSerol
 * @property Doctrine_Collection $SerolValor
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getTipo()         Returns the current record's "tipo" value
 * @method Doctrine_Collection getDonanteSerol() Returns the current record's "DonanteSerol" collection
 * @method Doctrine_Collection getSerolValor()   Returns the current record's "SerolValor" collection
 * @method Serol               setId()           Sets the current record's "id" value
 * @method Serol               setTipo()         Sets the current record's "tipo" value
 * @method Serol               setDonanteSerol() Sets the current record's "DonanteSerol" collection
 * @method Serol               setSerolValor()   Sets the current record's "SerolValor" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSerol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('serol');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DonanteSerol', array(
             'local' => 'id',
             'foreign' => 'serol_id'));

        $this->hasMany('SerolValor', array(
             'local' => 'id',
             'foreign' => 'serol_id'));
    }
}