<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrasplanteSerol', 'doctrine');

/**
 * BaseTrasplanteSerol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_trasplante
 * @property integer $id_serol
 * @property string $valor
 * 
 * @method integer         getIdTrasplante()  Returns the current record's "id_trasplante" value
 * @method integer         getIdSerol()       Returns the current record's "id_serol" value
 * @method string          getValor()         Returns the current record's "valor" value
 * @method TrasplanteSerol setIdTrasplante()  Sets the current record's "id_trasplante" value
 * @method TrasplanteSerol setIdSerol()       Sets the current record's "id_serol" value
 * @method TrasplanteSerol setValor()         Sets the current record's "valor" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteSerol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_serol');
        $this->hasColumn('id_trasplante', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('id_serol', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('valor', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}