<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteMarvirales', 'doctrine');

/**
 * BaseEvolucionTrasplanteMarvirales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property integer $hsv
 * @property string $aghbs
 * @property string $hbsac
 * @property string $hbcac
 * @property string $hvc
 * @property string $hiv
 * 
 * @method integer                       getIdtrasplante() Returns the current record's "idtrasplante" value
 * @method date                          getFecha()        Returns the current record's "fecha" value
 * @method integer                       getHsv()          Returns the current record's "hsv" value
 * @method string                        getAghbs()        Returns the current record's "aghbs" value
 * @method string                        getHbsac()        Returns the current record's "hbsac" value
 * @method string                        getHbcac()        Returns the current record's "hbcac" value
 * @method string                        getHvc()          Returns the current record's "hvc" value
 * @method string                        getHiv()          Returns the current record's "hiv" value
 * @method EvolucionTrasplanteMarvirales setIdtrasplante() Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteMarvirales setFecha()        Sets the current record's "fecha" value
 * @method EvolucionTrasplanteMarvirales setHsv()          Sets the current record's "hsv" value
 * @method EvolucionTrasplanteMarvirales setAghbs()        Sets the current record's "aghbs" value
 * @method EvolucionTrasplanteMarvirales setHbsac()        Sets the current record's "hbsac" value
 * @method EvolucionTrasplanteMarvirales setHbcac()        Sets the current record's "hbcac" value
 * @method EvolucionTrasplanteMarvirales setHvc()          Sets the current record's "hvc" value
 * @method EvolucionTrasplanteMarvirales setHiv()          Sets the current record's "hiv" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteMarvirales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_marvirales');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hsv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('aghbs', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('hbsac', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('hbcac', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('hvc', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('hiv', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}