<?php

/**
 * BaseConsulta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $sentencia
 * @property Doctrine_Collection $ConsultaCampo
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getSentencia()     Returns the current record's "sentencia" value
 * @method Doctrine_Collection getConsultaCampo() Returns the current record's "ConsultaCampo" collection
 * @method Consulta            setId()            Sets the current record's "id" value
 * @method Consulta            setNombre()        Sets the current record's "nombre" value
 * @method Consulta            setSentencia()     Sets the current record's "sentencia" value
 * @method Consulta            setConsultaCampo() Sets the current record's "ConsultaCampo" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsulta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consulta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('sentencia', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConsultaCampo', array(
             'local' => 'id',
             'foreign' => 'consulta_id'));
    }
}