<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrasplanteComplicaciones', 'doctrine');

/**
 * BaseTrasplanteComplicaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idpretrasplante
 * @property date $fecha
 * @property integer $medicacion
 * @property integer $internado
 * @property integer $dias_de_internacion
 * @property integer $evolucion
 * @property string $comentario
 * 
 * @method integer                  getId()                  Returns the current record's "id" value
 * @method integer                  getIdpretrasplante()     Returns the current record's "idpretrasplante" value
 * @method date                     getFecha()               Returns the current record's "fecha" value
 * @method integer                  getMedicacion()          Returns the current record's "medicacion" value
 * @method integer                  getInternado()           Returns the current record's "internado" value
 * @method integer                  getDiasDeInternacion()   Returns the current record's "dias_de_internacion" value
 * @method integer                  getEvolucion()           Returns the current record's "evolucion" value
 * @method string                   getComentario()          Returns the current record's "comentario" value
 * @method TrasplanteComplicaciones setId()                  Sets the current record's "id" value
 * @method TrasplanteComplicaciones setIdpretrasplante()     Sets the current record's "idpretrasplante" value
 * @method TrasplanteComplicaciones setFecha()               Sets the current record's "fecha" value
 * @method TrasplanteComplicaciones setMedicacion()          Sets the current record's "medicacion" value
 * @method TrasplanteComplicaciones setInternado()           Sets the current record's "internado" value
 * @method TrasplanteComplicaciones setDiasDeInternacion()   Sets the current record's "dias_de_internacion" value
 * @method TrasplanteComplicaciones setEvolucion()           Sets the current record's "evolucion" value
 * @method TrasplanteComplicaciones setComentario()          Sets the current record's "comentario" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteComplicaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_complicaciones');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idpretrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('medicacion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('internado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('dias_de_internacion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('evolucion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comentario', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}