<?php

/**
 * BaseEvolucionTrasplanteExamenesTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $EvolucionTrasplanteExamenes
 * 
 * @method integer                         getId()                          Returns the current record's "id" value
 * @method string                          getNombre()                      Returns the current record's "nombre" value
 * @method Doctrine_Collection             getEvolucionTrasplanteExamenes() Returns the current record's "EvolucionTrasplanteExamenes" collection
 * @method EvolucionTrasplanteExamenesTipo setId()                          Sets the current record's "id" value
 * @method EvolucionTrasplanteExamenesTipo setNombre()                      Sets the current record's "nombre" value
 * @method EvolucionTrasplanteExamenesTipo setEvolucionTrasplanteExamenes() Sets the current record's "EvolucionTrasplanteExamenes" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteExamenesTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_examenes_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EvolucionTrasplanteExamenes', array(
             'local' => 'id',
             'foreign' => 'evolucion_trasplante_examenes_tipo_id'));
    }
}