<?php

/**
 * BaseAntecedentesDeDonante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Donantes
 * @property Doctrine_Collection $DonanteAntecedentes
 * 
 * @method integer               getId()                  Returns the current record's "id" value
 * @method string                getNombre()              Returns the current record's "nombre" value
 * @method Doctrine_Collection   getDonantes()            Returns the current record's "Donantes" collection
 * @method Doctrine_Collection   getDonanteAntecedentes() Returns the current record's "DonanteAntecedentes" collection
 * @method AntecedentesDeDonante setId()                  Sets the current record's "id" value
 * @method AntecedentesDeDonante setNombre()              Sets the current record's "nombre" value
 * @method AntecedentesDeDonante setDonantes()            Sets the current record's "Donantes" collection
 * @method AntecedentesDeDonante setDonanteAntecedentes() Sets the current record's "DonanteAntecedentes" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAntecedentesDeDonante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('antecedentes_de_donante');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Donante as Donantes', array(
             'refClass' => 'DonanteAntecedentes',
             'local' => 'antecedente_de_donante_id',
             'foreign' => 'donante_id'));

        $this->hasMany('DonanteAntecedentes', array(
             'local' => 'id',
             'foreign' => 'antecedente_de_donante_id'));
    }
}