<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Donante', 'doctrine');

/**
 * BaseDonante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $tipo_donante
 * @property string $sexo_donante
 * @property integer $edad_donante
 * @property integer $enastab_hemod
 * @property integer $causa_muerte_donante
 * @property float $cr_p
 * @property string $otros
 * @property string $grupo_sang
 * @property string $relacion_filiar
 * @property integer $peso
 * @property integer $altura
 * 
 * @method string  getId()                   Returns the current record's "id" value
 * @method string  getTipoDonante()          Returns the current record's "tipo_donante" value
 * @method string  getSexoDonante()          Returns the current record's "sexo_donante" value
 * @method integer getEdadDonante()          Returns the current record's "edad_donante" value
 * @method integer getEnastabHemod()         Returns the current record's "enastab_hemod" value
 * @method integer getCausaMuerteDonante()   Returns the current record's "causa_muerte_donante" value
 * @method float   getCrP()                  Returns the current record's "cr_p" value
 * @method string  getOtros()                Returns the current record's "otros" value
 * @method string  getGrupoSang()            Returns the current record's "grupo_sang" value
 * @method string  getRelacionFiliar()       Returns the current record's "relacion_filiar" value
 * @method integer getPeso()                 Returns the current record's "peso" value
 * @method integer getAltura()               Returns the current record's "altura" value
 * @method Donante setId()                   Sets the current record's "id" value
 * @method Donante setTipoDonante()          Sets the current record's "tipo_donante" value
 * @method Donante setSexoDonante()          Sets the current record's "sexo_donante" value
 * @method Donante setEdadDonante()          Sets the current record's "edad_donante" value
 * @method Donante setEnastabHemod()         Sets the current record's "enastab_hemod" value
 * @method Donante setCausaMuerteDonante()   Sets the current record's "causa_muerte_donante" value
 * @method Donante setCrP()                  Sets the current record's "cr_p" value
 * @method Donante setOtros()                Sets the current record's "otros" value
 * @method Donante setGrupoSang()            Sets the current record's "grupo_sang" value
 * @method Donante setRelacionFiliar()       Sets the current record's "relacion_filiar" value
 * @method Donante setPeso()                 Sets the current record's "peso" value
 * @method Donante setAltura()               Sets the current record's "altura" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donante');
        $this->hasColumn('id', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tipo_donante', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('sexo_donante', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edad_donante', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('enastab_hemod', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('causa_muerte_donante', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('cr_p', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('otros', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grupo_sang', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('relacion_filiar', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('peso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('altura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}