<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cmv', 'doctrine');

/**
 * BaseCmv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trasplante
 * @property date $fecha
 * @property integer $diagnostico
 * @property integer $tm
 * @property integer $sindromeviral
 * @property integer $profilaxis
 * @property integer $droga
 * @property integer $diastm
 * @property string $efectosecundario
 * 
 * @method integer getTrasplante()       Returns the current record's "trasplante" value
 * @method date    getFecha()            Returns the current record's "fecha" value
 * @method integer getDiagnostico()      Returns the current record's "diagnostico" value
 * @method integer getTm()               Returns the current record's "tm" value
 * @method integer getSindromeviral()    Returns the current record's "sindromeviral" value
 * @method integer getProfilaxis()       Returns the current record's "profilaxis" value
 * @method integer getDroga()            Returns the current record's "droga" value
 * @method integer getDiastm()           Returns the current record's "diastm" value
 * @method string  getEfectosecundario() Returns the current record's "efectosecundario" value
 * @method Cmv     setTrasplante()       Sets the current record's "trasplante" value
 * @method Cmv     setFecha()            Sets the current record's "fecha" value
 * @method Cmv     setDiagnostico()      Sets the current record's "diagnostico" value
 * @method Cmv     setTm()               Sets the current record's "tm" value
 * @method Cmv     setSindromeviral()    Sets the current record's "sindromeviral" value
 * @method Cmv     setProfilaxis()       Sets the current record's "profilaxis" value
 * @method Cmv     setDroga()            Sets the current record's "droga" value
 * @method Cmv     setDiastm()           Sets the current record's "diastm" value
 * @method Cmv     setEfectosecundario() Sets the current record's "efectosecundario" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cmv');
        $this->hasColumn('trasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('diagnostico', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('tm', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('sindromeviral', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('profilaxis', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('droga', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('diastm', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('efectosecundario', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}