<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DonanteCausaMuerte', 'doctrine');

/**
 * BaseDonanteCausaMuerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $detalles
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method string             getDetalles() Returns the current record's "detalles" value
 * @method DonanteCausaMuerte setId()       Sets the current record's "id" value
 * @method DonanteCausaMuerte setDetalles() Sets the current record's "detalles" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonanteCausaMuerte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donante_causa_muerte');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 3,
             ));
        $this->hasColumn('detalles', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}