<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FechaControl', 'doctrine');

/**
 * BaseFechaControl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $fecha
 * @property integer $anos
 * @property integer $meses
 * @property integer $dias
 * 
 * @method integer      getId()    Returns the current record's "id" value
 * @method string       getFecha() Returns the current record's "fecha" value
 * @method integer      getAnos()  Returns the current record's "anos" value
 * @method integer      getMeses() Returns the current record's "meses" value
 * @method integer      getDias()  Returns the current record's "dias" value
 * @method FechaControl setId()    Sets the current record's "id" value
 * @method FechaControl setFecha() Sets the current record's "fecha" value
 * @method FechaControl setAnos()  Sets the current record's "anos" value
 * @method FechaControl setMeses() Sets the current record's "meses" value
 * @method FechaControl setDias()  Sets the current record's "dias" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFechaControl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fecha_control');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('fecha', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('anos', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('meses', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('dias', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}