<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pacientes', 'doctrine');

/**
 * BasePacientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $the
 * @property string $ci
 * @property string $nombre
 * @property string $apellido
 * @property integer $num_fnr
 * @property string $raza
 * @property string $sexo
 * @property date $fecha_nacimiento
 * @property date $fecha_dialisis
 * @property integer $nefropatia
 * @property string $grupo_sang
 * 
 * @method integer   getThe()              Returns the current record's "the" value
 * @method string    getCi()               Returns the current record's "ci" value
 * @method string    getNombre()           Returns the current record's "nombre" value
 * @method string    getApellido()         Returns the current record's "apellido" value
 * @method integer   getNumFnr()           Returns the current record's "num_fnr" value
 * @method string    getRaza()             Returns the current record's "raza" value
 * @method string    getSexo()             Returns the current record's "sexo" value
 * @method date      getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method date      getFechaDialisis()    Returns the current record's "fecha_dialisis" value
 * @method integer   getNefropatia()       Returns the current record's "nefropatia" value
 * @method string    getGrupoSang()        Returns the current record's "grupo_sang" value
 * @method Pacientes setThe()              Sets the current record's "the" value
 * @method Pacientes setCi()               Sets the current record's "ci" value
 * @method Pacientes setNombre()           Sets the current record's "nombre" value
 * @method Pacientes setApellido()         Sets the current record's "apellido" value
 * @method Pacientes setNumFnr()           Sets the current record's "num_fnr" value
 * @method Pacientes setRaza()             Sets the current record's "raza" value
 * @method Pacientes setSexo()             Sets the current record's "sexo" value
 * @method Pacientes setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Pacientes setFechaDialisis()    Sets the current record's "fecha_dialisis" value
 * @method Pacientes setNefropatia()       Sets the current record's "nefropatia" value
 * @method Pacientes setGrupoSang()        Sets the current record's "grupo_sang" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePacientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pacientes');
        $this->hasColumn('the', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ci', 'string', 12, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('num_fnr', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('raza', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_dialisis', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nefropatia', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('grupo_sang', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}