<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ComplicacionesNoInf', 'doctrine');

/**
 * BaseComplicacionesNoInf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tr_complicacion
 * @property integer $id_complicacion
 * 
 * @method integer             getIdTrComplicacion()   Returns the current record's "id_tr_complicacion" value
 * @method integer             getIdComplicacion()     Returns the current record's "id_complicacion" value
 * @method ComplicacionesNoInf setIdTrComplicacion()   Sets the current record's "id_tr_complicacion" value
 * @method ComplicacionesNoInf setIdComplicacion()     Sets the current record's "id_complicacion" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComplicacionesNoInf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('complicaciones_no_inf');
        $this->hasColumn('id_tr_complicacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_complicacion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}