<?php

/**
 * BaseTrasplanteComplicacionesConsulta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trasplante_id
 * @property integer $complicacion_id
 * @property string $complicacion_class
 * @property integer $dias_desde_trasplante
 * @property integer $meses_desde_trasplante
 * @property integer $years_desde_trasplante
 * 
 * @method integer                          getId()                     Returns the current record's "id" value
 * @method integer                          getTrasplanteId()           Returns the current record's "trasplante_id" value
 * @method integer                          getComplicacionId()         Returns the current record's "complicacion_id" value
 * @method string                           getComplicacionClass()      Returns the current record's "complicacion_class" value
 * @method integer                          getDiasDesdeTrasplante()    Returns the current record's "dias_desde_trasplante" value
 * @method integer                          getMesesDesdeTrasplante()   Returns the current record's "meses_desde_trasplante" value
 * @method integer                          getYearsDesdeTrasplante()   Returns the current record's "years_desde_trasplante" value
 * @method TrasplanteComplicacionesConsulta setId()                     Sets the current record's "id" value
 * @method TrasplanteComplicacionesConsulta setTrasplanteId()           Sets the current record's "trasplante_id" value
 * @method TrasplanteComplicacionesConsulta setComplicacionId()         Sets the current record's "complicacion_id" value
 * @method TrasplanteComplicacionesConsulta setComplicacionClass()      Sets the current record's "complicacion_class" value
 * @method TrasplanteComplicacionesConsulta setDiasDesdeTrasplante()    Sets the current record's "dias_desde_trasplante" value
 * @method TrasplanteComplicacionesConsulta setMesesDesdeTrasplante()   Sets the current record's "meses_desde_trasplante" value
 * @method TrasplanteComplicacionesConsulta setYearsDesdeTrasplante()   Sets the current record's "years_desde_trasplante" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteComplicacionesConsulta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_complicaciones_consulta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('complicacion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('complicacion_class', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('dias_desde_trasplante', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('meses_desde_trasplante', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('years_desde_trasplante', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}