<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Nefropatia', 'doctrine');

/**
 * BaseNefropatia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nefropatia
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getNefropatia() Returns the current record's "nefropatia" value
 * @method Nefropatia setId()         Sets the current record's "id" value
 * @method Nefropatia setNefropatia() Sets the current record's "nefropatia" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNefropatia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nefropatia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nefropatia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}