<?php

/**
 * BaseTrasplanteSerol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trasplante_id
 * @property integer $serol_id
 * @property integer $serol_valor_id
 * @property Trasplante $Trasplante
 * @property Serol $Serol
 * @property SerolValor $SerolValor
 * 
 * @method integer         getTrasplanteId()   Returns the current record's "trasplante_id" value
 * @method integer         getSerolId()        Returns the current record's "serol_id" value
 * @method integer         getSerolValorId()   Returns the current record's "serol_valor_id" value
 * @method Trasplante      getTrasplante()     Returns the current record's "Trasplante" value
 * @method Serol           getSerol()          Returns the current record's "Serol" value
 * @method SerolValor      getSerolValor()     Returns the current record's "SerolValor" value
 * @method TrasplanteSerol setTrasplanteId()   Sets the current record's "trasplante_id" value
 * @method TrasplanteSerol setSerolId()        Sets the current record's "serol_id" value
 * @method TrasplanteSerol setSerolValorId()   Sets the current record's "serol_valor_id" value
 * @method TrasplanteSerol setTrasplante()     Sets the current record's "Trasplante" value
 * @method TrasplanteSerol setSerol()          Sets the current record's "Serol" value
 * @method TrasplanteSerol setSerolValor()     Sets the current record's "SerolValor" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteSerol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_serol');
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('serol_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('serol_valor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trasplante', array(
             'local' => 'trasplante_id',
             'foreign' => 'id'));

        $this->hasOne('Serol', array(
             'local' => 'serol_id',
             'foreign' => 'id'));

        $this->hasOne('SerolValor', array(
             'local' => 'serol_valor_id',
             'foreign' => 'id'));
    }
}