<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ComplicacionesInf', 'doctrine');

/**
 * BaseComplicacionesInf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tr_complicacion
 * @property integer $infeccion
 * @property integer $germen
 * 
 * @method integer           getIdTrComplicacion()   Returns the current record's "id_tr_complicacion" value
 * @method integer           getInfeccion()          Returns the current record's "infeccion" value
 * @method integer           getGermen()             Returns the current record's "germen" value
 * @method ComplicacionesInf setIdTrComplicacion()   Sets the current record's "id_tr_complicacion" value
 * @method ComplicacionesInf setInfeccion()          Sets the current record's "infeccion" value
 * @method ComplicacionesInf setGermen()             Sets the current record's "germen" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComplicacionesInf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('complicaciones_inf');
        $this->hasColumn('id_tr_complicacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('infeccion', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('germen', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}