<?php

/**
 * BaseVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method string  getNombre() Returns the current record's "nombre" value
 * @method Version setId()     Sets the current record's "id" value
 * @method Version setNombre() Sets the current record's "nombre" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('version');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}