<?php

/**
 * BaseTrasplanteReoperacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trasplante_id
 * @property date $fecha
 * @property string $descripcion
 * @property integer $trasplante_complicacion_id
 * @property Trasplante $Trasplante
 * @property TrasplanteComplicaciones $TrasplanteComplicaciones
 * 
 * @method integer                  getId()                         Returns the current record's "id" value
 * @method integer                  getTrasplanteId()               Returns the current record's "trasplante_id" value
 * @method date                     getFecha()                      Returns the current record's "fecha" value
 * @method string                   getDescripcion()                Returns the current record's "descripcion" value
 * @method integer                  getTrasplanteComplicacionId()   Returns the current record's "trasplante_complicacion_id" value
 * @method Trasplante               getTrasplante()                 Returns the current record's "Trasplante" value
 * @method TrasplanteComplicaciones getTrasplanteComplicaciones()   Returns the current record's "TrasplanteComplicaciones" value
 * @method TrasplanteReoperacion    setId()                         Sets the current record's "id" value
 * @method TrasplanteReoperacion    setTrasplanteId()               Sets the current record's "trasplante_id" value
 * @method TrasplanteReoperacion    setFecha()                      Sets the current record's "fecha" value
 * @method TrasplanteReoperacion    setDescripcion()                Sets the current record's "descripcion" value
 * @method TrasplanteReoperacion    setTrasplanteComplicacionId()   Sets the current record's "trasplante_complicacion_id" value
 * @method TrasplanteReoperacion    setTrasplante()                 Sets the current record's "Trasplante" value
 * @method TrasplanteReoperacion    setTrasplanteComplicaciones()   Sets the current record's "TrasplanteComplicaciones" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrasplanteReoperacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trasplante_reoperacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('descripcion', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('trasplante_complicacion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trasplante', array(
             'local' => 'trasplante_id',
             'foreign' => 'id'));

        $this->hasOne('TrasplanteComplicaciones', array(
             'local' => 'trasplante_complicacion_id',
             'foreign' => 'id'));
    }
}