<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ResultadoPbr', 'doctrine');

/**
 * BaseResultadoPbr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $grado
 * @property string $criterio
 * 
 * @method integer      getId()       Returns the current record's "id" value
 * @method string       getGrado()    Returns the current record's "grado" value
 * @method string       getCriterio() Returns the current record's "criterio" value
 * @method ResultadoPbr setId()       Sets the current record's "id" value
 * @method ResultadoPbr setGrado()    Sets the current record's "grado" value
 * @method ResultadoPbr setCriterio() Sets the current record's "criterio" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResultadoPbr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resultado_pbr');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('grado', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('criterio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}