<?php

/**
 * BaseInduccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Trasplante
 * @property Doctrine_Collection $TrasplanteInduccion
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method Doctrine_Collection getTrasplante()          Returns the current record's "Trasplante" collection
 * @method Doctrine_Collection getTrasplanteInduccion() Returns the current record's "TrasplanteInduccion" collection
 * @method Induccion           setId()                  Sets the current record's "id" value
 * @method Induccion           setNombre()              Sets the current record's "nombre" value
 * @method Induccion           setTrasplante()          Sets the current record's "Trasplante" collection
 * @method Induccion           setTrasplanteInduccion() Sets the current record's "TrasplanteInduccion" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInduccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('induccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Trasplante', array(
             'refClass' => 'TrasplanteInduccion',
             'local' => 'induccion_id',
             'foreign' => 'trasplante_id'));

        $this->hasMany('TrasplanteInduccion', array(
             'local' => 'id',
             'foreign' => 'induccion_id'));
    }
}