<?php

/**
 * BaseEvolucionTrasplanteExamenes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $trasplante_id
 * @property date $fecha
 * @property integer $evolucion_trasplante_examenes_tipo_id
 * @property enum $tipo
 * @property string $comentario
 * @property Trasplante $Trasplante
 * 
 * @method integer                     getId()                                    Returns the current record's "id" value
 * @method integer                     getTrasplanteId()                          Returns the current record's "trasplante_id" value
 * @method date                        getFecha()                                 Returns the current record's "fecha" value
 * @method integer                     getEvolucionTrasplanteExamenesTipoId()     Returns the current record's "evolucion_trasplante_examenes_tipo_id" value
 * @method enum                        getTipo()                                  Returns the current record's "tipo" value
 * @method string                      getComentario()                            Returns the current record's "comentario" value
 * @method Trasplante                  getTrasplante()                            Returns the current record's "Trasplante" value
 * @method EvolucionTrasplanteExamenes setId()                                    Sets the current record's "id" value
 * @method EvolucionTrasplanteExamenes setTrasplanteId()                          Sets the current record's "trasplante_id" value
 * @method EvolucionTrasplanteExamenes setFecha()                                 Sets the current record's "fecha" value
 * @method EvolucionTrasplanteExamenes setEvolucionTrasplanteExamenesTipoId()     Sets the current record's "evolucion_trasplante_examenes_tipo_id" value
 * @method EvolucionTrasplanteExamenes setTipo()                                  Sets the current record's "tipo" value
 * @method EvolucionTrasplanteExamenes setComentario()                            Sets the current record's "comentario" value
 * @method EvolucionTrasplanteExamenes setTrasplante()                            Sets the current record's "Trasplante" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteExamenes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_examenes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trasplante_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('evolucion_trasplante_examenes_tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'Normal',
              1 => 'Patologico',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('comentario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Trasplante', array(
             'local' => 'trasplante_id',
             'foreign' => 'id'));
    }
}