<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteCmv', 'doctrine');

/**
 * BaseEvolucionTrasplanteCmv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property integer $igg_cmv
 * @property integer $igm_cmv
 * @property integer $pcr_cmv
 * @property integer $ag_pp65
 * 
 * @method integer                getIdtrasplante() Returns the current record's "idtrasplante" value
 * @method date                   getFecha()        Returns the current record's "fecha" value
 * @method integer                getIggCmv()       Returns the current record's "igg_cmv" value
 * @method integer                getIgmCmv()       Returns the current record's "igm_cmv" value
 * @method integer                getPcrCmv()       Returns the current record's "pcr_cmv" value
 * @method integer                getAgPp65()       Returns the current record's "ag_pp65" value
 * @method EvolucionTrasplanteCmv setIdtrasplante() Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteCmv setFecha()        Sets the current record's "fecha" value
 * @method EvolucionTrasplanteCmv setIggCmv()       Sets the current record's "igg_cmv" value
 * @method EvolucionTrasplanteCmv setIgmCmv()       Sets the current record's "igm_cmv" value
 * @method EvolucionTrasplanteCmv setPcrCmv()       Sets the current record's "pcr_cmv" value
 * @method EvolucionTrasplanteCmv setAgPp65()       Sets the current record's "ag_pp65" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteCmv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_cmv');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('igg_cmv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('igm_cmv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('pcr_cmv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ag_pp65', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}