<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvolucionTrasplanteEcodopler', 'doctrine');

/**
 * BaseEvolucionTrasplanteEcodopler
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtrasplante
 * @property date $fecha
 * @property string $estructura
 * @property integer $dilatacion
 * @property integer $colecciones
 * @property string $eje_arterial
 * @property string $eje_venoso
 * @property string $arteria_renal
 * @property string $vena_renal
 * @property string $anast_venosa
 * @property string $anast_renosa
 * @property float $indice
 * @property string $otros
 * 
 * @method integer                      getIdtrasplante()  Returns the current record's "idtrasplante" value
 * @method date                         getFecha()         Returns the current record's "fecha" value
 * @method string                       getEstructura()    Returns the current record's "estructura" value
 * @method integer                      getDilatacion()    Returns the current record's "dilatacion" value
 * @method integer                      getColecciones()   Returns the current record's "colecciones" value
 * @method string                       getEjeArterial()   Returns the current record's "eje_arterial" value
 * @method string                       getEjeVenoso()     Returns the current record's "eje_venoso" value
 * @method string                       getArteriaRenal()  Returns the current record's "arteria_renal" value
 * @method string                       getVenaRenal()     Returns the current record's "vena_renal" value
 * @method string                       getAnastVenosa()   Returns the current record's "anast_venosa" value
 * @method string                       getAnastRenosa()   Returns the current record's "anast_renosa" value
 * @method float                        getIndice()        Returns the current record's "indice" value
 * @method string                       getOtros()         Returns the current record's "otros" value
 * @method EvolucionTrasplanteEcodopler setIdtrasplante()  Sets the current record's "idtrasplante" value
 * @method EvolucionTrasplanteEcodopler setFecha()         Sets the current record's "fecha" value
 * @method EvolucionTrasplanteEcodopler setEstructura()    Sets the current record's "estructura" value
 * @method EvolucionTrasplanteEcodopler setDilatacion()    Sets the current record's "dilatacion" value
 * @method EvolucionTrasplanteEcodopler setColecciones()   Sets the current record's "colecciones" value
 * @method EvolucionTrasplanteEcodopler setEjeArterial()   Sets the current record's "eje_arterial" value
 * @method EvolucionTrasplanteEcodopler setEjeVenoso()     Sets the current record's "eje_venoso" value
 * @method EvolucionTrasplanteEcodopler setArteriaRenal()  Sets the current record's "arteria_renal" value
 * @method EvolucionTrasplanteEcodopler setVenaRenal()     Sets the current record's "vena_renal" value
 * @method EvolucionTrasplanteEcodopler setAnastVenosa()   Sets the current record's "anast_venosa" value
 * @method EvolucionTrasplanteEcodopler setAnastRenosa()   Sets the current record's "anast_renosa" value
 * @method EvolucionTrasplanteEcodopler setIndice()        Sets the current record's "indice" value
 * @method EvolucionTrasplanteEcodopler setOtros()         Sets the current record's "otros" value
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvolucionTrasplanteEcodopler extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evolucion_trasplante_ecodopler');
        $this->hasColumn('idtrasplante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estructura', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('dilatacion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('colecciones', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('eje_arterial', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('eje_venoso', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('arteria_renal', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('vena_renal', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('anast_venosa', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('anast_renosa', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('indice', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('otros', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}