<?php

/**
 * BaseConsultaCampoTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $tipo
 * @property Doctrine_Collection $ConsultaCampo
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getTipo()          Returns the current record's "tipo" value
 * @method Doctrine_Collection getConsultaCampo() Returns the current record's "ConsultaCampo" collection
 * @method ConsultaCampoTipo   setId()            Sets the current record's "id" value
 * @method ConsultaCampoTipo   setNombre()        Sets the current record's "nombre" value
 * @method ConsultaCampoTipo   setTipo()          Sets the current record's "tipo" value
 * @method ConsultaCampoTipo   setConsultaCampo() Sets the current record's "ConsultaCampo" collection
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsultaCampoTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consulta_campo_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('tipo', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConsultaCampo', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));
    }
}