array(18) { 
  ["id"]=> string(1) "1" 
  ["paciente_id"]=> string(1) "1" 
  ["the"]=> string(1) "1" 
  ["fecha_ingreso_lista"]=> string(10) "1999-05-01" 
  ["fecha_egreso"]=> string(10) "2000-02-09" 
  ["modalidad_d"]=> string(2) "HD" 
  ["diabetes"]=> string(2) "No" 
  ["imc"]=> string(13) "entre 20 y 25" 
  ["origen"]=> string(4) "IAMC" 
  ["pbr"]=> string(1) "0" 
  ["hta"]=> string(1) "0" 
  ["obesidad"]=> string(1) "0" 
  ["dislipemia"]=> string(1) "0" 
  ["tabaquismo"]=> string(1) "0" 
  ["iam"]=> string(1) "0" 
  ["ave"]=> string(1) "0" 
  ["revasc_cardio"]=> string(1) "0" 
  ["meses_en_lista"]=> string(1) "9" 
} 
