<?php

/**
 * AntecedentesDeDonanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AntecedentesDeDonanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AntecedentesDeDonanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AntecedentesDeDonante');
    }
}