<?php

/**
 * CmvdiagnosticoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmvdiagnosticoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmvdiagnosticoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cmvdiagnostico');
    }
}