<?php

/**
 * CmvdrogasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmvdrogasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmvdrogasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cmvdrogas');
    }
}