<?php

/**
 * CmvDiagnosticoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmvDiagnosticoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmvDiagnosticoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmvDiagnostico');
    }
}