<?php

/**
 * CmvemfermedadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmvemfermedadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmvemfermedadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cmvemfermedades');
    }
}