<?php

/**
 * CmvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cmv');
    }
}