<?php

/**
 * ComplicacionesNoInfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplicacionesNoInfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplicacionesNoInfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplicacionesNoInf');
    }
}