<?php

/**
 * ComplicacionesTiposTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplicacionesTiposTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplicacionesTiposTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplicacionesTipos');
    }
}