<?php

/**
 * ComplicacionesInfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplicacionesInfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplicacionesInfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplicacionesInf');
    }
}