<?php

/**
 * ComplicacionesNoInfecciosasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplicacionesNoInfecciosasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplicacionesNoInfecciosasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplicacionesNoInfecciosas');
    }
}