<?php

/**
 * ComplicacionesTiposTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplicacionesTiposTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplicacionesTiposTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplicacionesTipos');
    }
	
	public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("ct")
                ->addWhere("ct.id = ?", $id);

      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    } 
	
	public function retrieveAll($hydrationMode = Doctrine_Core::HYDRATE_RECORD)
	{
	  $query = $this->createQuery("ct");
	  $query->setHydrationMode($hydrationMode);
	  return $query->execute();
	} 	
}