<?php

/**
 * ConsultaCampoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsultaCampoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsultaCampoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConsultaCampo');
    }
}