<?php

/**
 * DatosutilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatosutilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatosutilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Datosutiles');
    }
}