<?php

/**
 * DonanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Donante');
    }
}