<?php

/**
 * DonanteOrganosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonanteOrganosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonanteOrganosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DonanteOrganos');
    }
}