<?php

/**
 * DonanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Donante');
    }
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("d")
                ->addWhere("d.id = ?", $id);

      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }     
}
