<?php

/**
 * DonanteOrganosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonanteOrganosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonanteOrganosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DonanteOrganos');
    }
	
	public function retrieveAll($hydrationMode = Doctrine_Core::HYDRATE_RECORD)
	{
	  $query = $this->createQuery("do");
	  $query->setHydrationMode($hydrationMode);
	  return $query->execute();
	}	
}