<?php

/**
 * DonanteSerolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonanteSerolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonanteSerolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DonanteSerol');
    }
    
    public function retrieveAllSeroles($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("ds")
                  ->addWhere("ds.donante_id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->execute();      
    }
}
