<?php

/**
 * EvolucionTrasplanteTxtoraxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvolucionTrasplanteTxtoraxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvolucionTrasplanteTxtoraxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvolucionTrasplanteTxtorax');
    }
    
    public function retrieveAll($trasplanteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("etTxTorax");
      $query->addWhere("etTxTorax.trasplante_id = ?", $trasplanteId );
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("etTxTorax")
                ->addWhere("etTxTorax.id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }
}