<?php

/**
 * EvolucionTrasplanteEcografiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvolucionTrasplanteEcografiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvolucionTrasplanteEcografiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvolucionTrasplanteEcografia');
    }
    
    public function retrieveAll($trasplanteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("etEcografia");
      $query->addWhere("etEcografia.trasplante_id = ?", $trasplanteId );
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("etEcografia")
                ->addWhere("etEcografia.id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }
}