<?php

/**
 * EvolucionTrasplanteParaclinicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvolucionTrasplanteParaclinicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvolucionTrasplanteParaclinicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvolucionTrasplanteParaclinica');
    }
}