<?php

/**
 * EvolucionTrasplanteTxtoraxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvolucionTrasplanteTxtoraxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvolucionTrasplanteTxtoraxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvolucionTrasplanteTxtorax');
    }
}