<?php

/**
 * EvolucionTrasplanteExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvolucionTrasplanteExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvolucionTrasplanteExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvolucionTrasplanteExamenes');
    }
}