<?php

/**
 * FechaControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FechaControlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FechaControlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FechaControl');
    }
}