<?php

/**
 * GermenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GermenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GermenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Germenes');
    }
}