<?php

/**
 * InduccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InduccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InduccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Induccion');
    }
    
    public function retriveAllInduccionesByTrasplanteId($trasplanteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("i")
                ->select("i.*")
                ->addFrom("TrasplanteInduccion t")
                ->addWhere("i.id = t.induccion_id")
                ->addWhere("t.trasplante_id = ?", $trasplanteId);
 
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }    
}
