<?php

/**
 * InfeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Infeccion');
    }
	
	public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("ii")
                ->addWhere("ii.id = ?", $id);

      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    } 
	
	public function retrieveAll($hydrationMode = Doctrine_Core::HYDRATE_RECORD)
	{
	  $query = $this->createQuery("ii");
	  $query->setHydrationMode($hydrationMode);
	  return $query->execute();
	}	
}