<?php

/**
 * InfeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Infeccion');
    }
}