<?php

/**
 * MedicacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicaciones');
    }
}