<?php

/**
 * NefropatiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NefropatiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NefropatiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nefropatia');
    }
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("N")
                ->addWhere("N.id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }  

    public function retriveByPacienteId($pacienteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("N")
                ->select("N.*")
                ->addFrom("Pacientes p")
                ->addWhere("N.id = p.nefropatia_id")
                ->addWhere("p.id = ?", $pacienteId);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }  
        
}
