<?php

/**
 * OrganosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organos');
    }
}