<?php

/**
 * PacientePerdidaInjertoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientePerdidaInjertoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientePerdidaInjertoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PacientePerdidaInjerto');
    }
    
    public function retriveByPacienteId($pacienteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("PP")
                ->addWhere("PP.paciente_id = ?", $pacienteId);
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }     
}
