<?php

/**
 * PacientepretrasplanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientepretrasplanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientepretrasplanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pacientepretrasplante');
    }
    
    public function retrieveAllPacientepreTrasplantesIds()
    {
        $query = $this->createQuery("pt");
        $query->select("pt.id");
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }    
}
