<?php

/**
 * PacientepretrasplanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientepretrasplanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientepretrasplanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pacientepretrasplante');
    }
    
    public function retrieveAllPacientepreTrasplantesIds()
    {
        $query = $this->createQuery("pt");
        $query->select("pt.id");
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }    

    public function retrieveAllPacientepreTrasplantesIdsByYear($year)
    {
        $start = $year. "-1-1";
        $end = $year. "-12-31";
        $query = $this->createQuery("pt");
        $query->select("pt.id")
          ->addFrom("Trasplante t")
          ->addWhere("pt.id = t.paciente_pre_trasplante_id")
          ->addWhere("t.fecha > ?", $start)
          ->addWhere("t.fecha < ?", $end);
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }   
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("pt")
                ->addWhere("pt.id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }
    
    public function retrieveNumberPreTrasplantesOfPaciente($pacienteId)
    {
        $query = $this->createQuery("pt");
        $query->select("count(pt.id)")->addWhere("pt.paciente_id = ?", $pacienteId);
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }         
}
