<?php

/**
 * PacienteCausaMuerteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteCausaMuerteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteCausaMuerteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PacienteCausaMuerte');
    }

    public function retriveById($causaId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("pcm")
                ->addWhere("pcm.id = ?", $causaId);

      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }
}