<?php

/**
 * PacienteCausaPerdidaInjertoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteCausaPerdidaInjertoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteCausaPerdidaInjertoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PacienteCausaPerdidaInjerto');
    }
}