<?php

/**
 * PacienteMuerteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteMuerteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteMuerteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PacienteMuerte');
    }
}