<?php

/**
 * SerolValorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SerolValorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SerolValorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SerolValor');
    }
}