<?php

/**
 * TrasplanteComplicacionesConsultaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteComplicacionesConsultaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteComplicacionesConsultaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteComplicacionesConsulta');
    }
    
    public function getByObjectClassAndId($objectId, $objectClass)
    {
        return $this->createQuery('tcc')
                ->addWhere('tcc.complicacion_id = ?', $objectId)
                ->addWhere('tcc.complicacion_class = ?', $objectClass)
                ->fetchOne();
    }
}