<?php

/**
 * TrasplanteInduccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteInduccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteInduccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteInduccion');
    }
}