<?php

/**
 * TrasplanteComplicacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteComplicacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteComplicacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteComplicaciones');
    }
}