<?php

/**
 * TrasplanteSerolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteSerolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteSerolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteSerol');
    }
}