<?php

/**
 * TrasplanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trasplante');
    }
    
    
    public function retrieveAllTrasplantesIds()
    {
        $query = $this->createQuery("T");
        $query->select("T.id");
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }
    
    public function retrieveTrasplanteFechaFromPreTrasplanteId($paciente_pre_trasplante_id)
    {
        $query = $this->createQuery("T");
        $query->select("T.fecha");
        $query->addWhere("T.paciente_pre_trasplante_id = ?", $paciente_pre_trasplante_id);
        $query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
        return $query->execute();
    }
    
    public function retriveById($id, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("T")
                ->addWhere("T.id = ?", $id);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }  

    public function retriveByPacientePreTrasplanteId($PreTrasplanteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("T")
                ->select("T.*")
                ->addWhere("T.paciente_pre_trasplante_id = ?", $PreTrasplanteId);
      $query->setHydrationMode($hydrationMode);
      return $query->fetchOne();
    }
    
    public function retriveByPacientePreTrasplanteIdAndDate($PreTrasplanteId, $date, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("T")
                ->select("T.*")
                ->addWhere("T.paciente_pre_trasplante_id = ?", $PreTrasplanteId)
                ->addWhere("T.fecha = ?", $date)
                ->limit(1);
      $query->setHydrationMode($hydrationMode);
      //var_dump($query);
      return $query->fetchOne();
    }
    
    public function retriveAll($hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("T");
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    } 
}
