<?php

/**
 * TrasplanteComplicacionesNoInfecciosasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteComplicacionesNoInfecciosasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteComplicacionesNoInfecciosasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteComplicacionesNoInfecciosas');
    }
}