<?php

/**
 * Trasplante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trasplante extends BaseTrasplante
{
  public function preSave($event) {
    parent::preSave($event);
    //Obtengo a la persona
    $paciente = $this->getPacientepretrasplante()->getPacientes();
    $edad = basicFunction::calculateDifferenceInYears($paciente->getFechaNacimiento(), $this->getFecha());
    $this->setEdadReceptor($edad);
    
  }

  
  public function postSave($event) 
  {
    parent::postSave($event);
    //Obtengo la fecha.
    $fecha = $this->getFecha();
    //Obtengo el pretrasplante
    $pretrasplante = $this->getPacientepretrasplante();
    $pretrasplante->setFechaEgreso($fecha);
    $pretrasplante->save();
  }

}
