<?php

/**
 * TrasplanteReoperacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasplanteReoperacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasplanteReoperacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrasplanteReoperacion');
    }
	
	public function retrieveReoperacionesFromTrasplante($trasplanteId, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("tr")
                ->addWhere("tr.trasplante_id = ?", $trasplanteId);

      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }    
}