<?php

/**
 * Version
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transplantes
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Version extends BaseVersion
{
    
    public function doProgramUpdate()
    {
        if(updatesHandler::versionExists($this->getNombre()))
        {
            if($this->getNombre() == updatesHandler::PRIMERA)
            {
                return $this->doFirstUpdate();
            }
        }
        return false;
    }
    
    private function doFirstUpdate()
    {
        //Como no hay que actualizar nada lo que tiene que pasar es
        //que devuelva true
        
        return true;
    }
}
