<?php

/**
 * mdMediaYouTubeVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaYouTubeVideoTable extends PluginmdMediaYouTubeVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaYouTubeVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaYouTubeVideo');
    }
}