InjertoEvolucion:
  tableName: injerto_evolucion
  columns:
    pretrasplante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    tm:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tm_cual:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    gp_de_novo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    recidiva_gp_de_novo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ra:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    rc:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tratamiento:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    trasplante:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false


InjertoEvolucionPbr:
  tableName: injerto_evolucion_pbr
  columns:
    pretrasplante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    resultado_pbr:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false


TrasplanteReoperacion:
  tableName: trasplante_reoperacion
  columns:
    id_trasplante:
      type: integer(3)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    descripcion:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    complicacion:
      type: integer(3)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: true
      autoincrement: false

######## DE ACA PARA ABAJO NO SE SI VA
Consultas:

  tableName: consultas
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sentencia:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipos:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombres:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Datosutiles:

  tableName: datosutiles
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    password:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: pass
      notnull: true
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    root:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  
FechaControl:
  tableName: fecha_control
  columns:
    id:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    anos:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    meses:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dias:
      type: integer(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
